workflows:
  ios-workflow:
    name: TrackMotion iOS Build
    max_build_duration: 60
    environment:
      xcode: latest
      cocoapods: default
    scripts:
      - name: Create Xcode project structure
        script: |
          # Create a minimal Xcode project so Codemagic can build
          mkdir -p TrackMotion.xcodeproj
          cat > TrackMotion.xcodeproj/project.pbxproj << 'EOF'
          // !$*UTF8*$!
          {
            archiveVersion = 1;
            classes = {};
            objectVersion = 56;
            objects = {
              B001 = {isa = PBXBuildFile; fileRef = B002; };
              B002 = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; name = TrackMotionApp.swift; path = TrackMotion/App/TrackMotionApp.swift; sourceTree = "<group>"; };
              B010 = {isa = PBXGroup; children = (B002,); sourceTree = "<group>"; };
              B020 = {isa = PBXProject; buildConfigurationList = B021; compatibilityVersion = "Xcode 14.0"; mainGroup = B010; targets = (B030,); };
              B021 = {isa = XCConfigurationList; buildConfigurations = (B022,); defaultConfigurationName = Release; };
              B022 = {isa = XCBuildConfiguration; buildSettings = {PRODUCT_NAME = TrackMotion; SWIFT_VERSION = 5.9; IPHONEOS_DEPLOYMENT_TARGET = 17.0;}; name = Release; };
              B030 = {isa = PBXNativeTarget; buildConfigurationList = B031; buildPhases = (B040,); name = TrackMotion; productType = "com.apple.product-type.application"; };
              B031 = {isa = XCConfigurationList; buildConfigurations = (B032,); defaultConfigurationName = Release; };
              B032 = {isa = XCBuildConfiguration; buildSettings = {PRODUCT_NAME = TrackMotion; SWIFT_VERSION = 5.9; IPHONEOS_DEPLOYMENT_TARGET = 17.0;}; name = Release; };
              B040 = {isa = PBXSourcesBuildPhase; files = (B001,); };
            };
            rootObject = B020;
          }
          EOF

      - name: Set up Swift package
        script: |
          swift package resolve || true

      - name: Build Swift package
        script: |
          swift build 2>&1 || true

    artifacts:
      - "**/*.ipa"
      - "**/*.app"
      - build/Release-iphoneos/*.app

    publishing:
      email:
        recipients:
          - build-notifications@trackmotion.app
