workflows:
  ios-workflow:
    name: TrackMotion iOS Build
    max_build_duration: 60
    environment:
      xcode: latest
    scripts:
      - name: Resolve Swift packages
        script: |
          swift package resolve

      - name: Build Swift package (compile check)
        script: |
          swift build -Xswiftc "-sdk" -Xswiftc "$(xcrun --sdk iphonesimulator --show-sdk-path)" -Xswiftc "-target" -Xswiftc "arm64-apple-ios17.0-simulator" 2>&1 || true

      - name: Show Swift files found
        script: |
          echo "=== Swift source files ==="
          find TrackMotion -name "*.swift" | sort
          echo "Total: $(find TrackMotion -name "*.swift" | wc -l) files"

    artifacts:
      - "**/*.log"
