workflows:
  ios-workflow:
    name: TrackMotion iOS Build
    max_build_duration: 60
    environment:
      xcode: latest
    scripts:
      - name: Resolve Swift packages
        script: |
          swift package resolve

      - name: Build for iOS Simulator
        script: |
          SDK=$(xcrun --sdk iphonesimulator --show-sdk-path)
          swift build \
            -Xswiftc "-sdk" \
            -Xswiftc "$SDK" \
            -Xswiftc "-target" \
            -Xswiftc "arm64-apple-ios17.0-simulator" \
            -Xswiftc "-F" \
            -Xswiftc "$SDK/System/Library/Frameworks"

      - name: Show compiled files
        script: |
          echo "=== Swift source files ==="
          find TrackMotion -name "*.swift" | sort
          echo "Total: $(find TrackMotion -name "*.swift" | wc -l) files"

    artifacts:
      - "**/*.log"
