workflows:
  ios-workflow:
    name: TrackMotion iOS Build
    max_build_duration: 60
    environment:
      xcode: 16.2
    scripts:
      - name: Generate Xcode project with xcodegen
        script: |
          # Install xcodegen if not present
          if ! command -v xcodegen &> /dev/null; then
            brew install xcodegen
          fi

          # Create project.yml for xcodegen
          cat > project.yml << 'EOF'
          name: TrackMotion
          options:
            bundleIdPrefix: com.trackmotion
            deploymentTarget:
              iOS: "17.0"
          packages:
            swift-numerics:
              url: https://github.com/apple/swift-numerics
              from: 1.0.2
            swift-algorithms:
              url: https://github.com/apple/swift-algorithms
              from: 1.2.0
          targets:
            TrackMotion:
              type: application
              platform: iOS
              deploymentTarget: "17.0"
              sources:
                - path: TrackMotion
              dependencies:
                - package: swift-numerics
                  product: RealModule
                - package: swift-algorithms
                  product: Algorithms
              settings:
                base:
                  PRODUCT_BUNDLE_IDENTIFIER: com.trackmotion.app
                  SWIFT_VERSION: 5.9
                  IPHONEOS_DEPLOYMENT_TARGET: 17.0
                  ENABLE_PREVIEWS: YES
                  INFOPLIST_FILE: TrackMotion/Info.plist
          EOF

      - name: Create Info.plist
        script: |
          cat > TrackMotion/Info.plist << 'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>CFBundleName</key>
            <string>TrackMotion</string>
            <key>CFBundleIdentifier</key>
            <string>com.trackmotion.app</string>
            <key>CFBundleVersion</key>
            <string>1</string>
            <key>CFBundleShortVersionString</key>
            <string>1.0</string>
            <key>CFBundleExecutable</key>
            <string>$(EXECUTABLE_NAME)</string>
            <key>CFBundlePackageType</key>
            <string>APPL</string>
            <key>LSRequiresIPhoneOS</key>
            <true/>
            <key>UILaunchScreen</key>
            <dict/>
            <key>NSCameraUsageDescription</key>
            <string>TrackMotion needs camera access to record and analyze sprint mechanics.</string>
            <key>NSSpeechRecognitionUsageDescription</key>
            <string>TrackMotion uses speech for voice coaching feedback.</string>
            <key>NSMicrophoneUsageDescription</key>
            <string>TrackMotion needs microphone access for video recording.</string>
            <key>UIRequiredDeviceCapabilities</key>
            <array>
              <string>armv7</string>
            </array>
            <key>UISupportedInterfaceOrientations</key>
            <array>
              <string>UIInterfaceOrientationPortrait</string>
              <string>UIInterfaceOrientationLandscapeLeft</string>
              <string>UIInterfaceOrientationLandscapeRight</string>
            </array>
          </dict>
          </plist>
          EOF

      - name: Generate Xcode project
        script: |
          xcodegen generate

      - name: Build for iOS Simulator
        script: |
          xcodebuild \
            -project TrackMotion.xcodeproj \
            -scheme TrackMotion \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
            -configuration Debug \
            CODE_SIGNING_ALLOWED=NO \
            build | xcpretty

    artifacts:
      - build/Debug-iphonesimulator/*.app
